---
apiVersion: v1
kind: Service
metadata:
  name: basic-grpc
  namespace: {{ .Values.namespace }}
  labels:
    app: basic-grpc
spec:
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: basic-grpc
